### ISSUE TITLE
Создать понятную файловую структуру

### ISSUE THREAD

**Issue by bittermil** [wendy-bear/Week-9-project-1#1]
Создать:
- структуру папок: img, assets, папка для страниц
- html файлы для страниц
- общий файл и файл со стилями

**Comment by kia-master** [comment]
Общий файл со стилями будет лежать в **/assets/styles**
На страницах стили будут наследоваться от главного и содержать свой css с уникальностями.

**Comment by kia-master** [comment]
Что делать с папкой bookshop? ))
