### ISSUE TITLE
Подготовить изображения для страниц

### ISSUE THREAD

**Issue by bittermil** [wendy-bear/Week-9-project-1#2]
- выгрузить из макетов и найти в интернете замену обрезанным изображениям.
- загрузить изображения в соответствующие папки: общие, иконки, уникальные изображения

**Comment by kia-master** [comment]
Сделала так: картинки в папке **assets/image**

Разбила на следующие папки:

- **profile_page** (уникальные картинки для страницы profile)
- **book_page** (уникальные картинки для страницы book)
- **home_page** (уникальные картинки для  главной страницы home)
- **coverbooks** (все обложки книг, выявила закономерность - что на каждой странице - обложки одинаковые, целесообразно положить в одну папку и из нее брать. Размер у всех большой.)
- **footer** (картинки для футера)
- **header** (картинки для хидера)
